'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {Store,validateCandidate,months,releaseTime,slotFromHref,classifyResult,verifyReview}=require('../core.cjs');
const {retryAfter,Gate}=require('../booking.cjs');
const {Notifier,createServer}=require('../server.cjs');
const sample={family:'TESTOV',given:'TEST',phone:'+998901234567',email:'test@example.invalid',passport:'AA1234567'};
function db(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jp-agent-test-'));const store=new Store(dir);t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});return store;}
test('candidate validation preserves exact values and rejects partial passports',()=>{assert.deepEqual(validateCandidate(sample),sample);assert.throws(()=>validateCandidate({...sample,passport:'1234567'}));assert.throws(()=>validateCandidate({...sample,email:'bad'}));});
test('Tashkent month rollover and next 18:00 are timezone independent',()=>{assert.deepEqual(months(new Date('2026-12-31T20:00:00Z')),['2027-01-01','2027-02-01']);assert.equal(releaseTime(new Date('2026-09-16T12:00:00Z')),'2026-09-16T13:00:00.000Z');assert.equal(releaseTime(new Date('2026-09-16T15:00:00Z')),'2026-09-17T13:00:00.000Z');});
test('only real Short stay option links pass category/date checks',()=>{const url='https://uzembassyryouji.rsvsys.jp/reservations/option?event_id=20&event_plan_id=19&date=2026%2F09%2F23&time_from=10%3A00';assert.equal(slotFromHref(url,'2026-09-16').date,'2026-09-23');assert.equal(slotFromHref(url.replace('event_id=20','event_id=22'),'2026-09-16'),null);assert.equal(slotFromHref(url.replace('uzembassyryouji.rsvsys.jp','evil.example'),'2026-09-16'),null);assert.equal(slotFromHref(url,'2026-09-24'),null);});
test('success requires a terminal page, never a confirmation or general text',()=>{assert.equal(classifyResult({url:'/reservations/complete',heading:'予約完了'}),'booked');assert.equal(classifyResult({url:'/reservations/confirm',heading:'Reservation confirmed',hasReserve:true}),'uncertain');assert.equal(classifyResult({url:'/reservations/user/guest',heading:'Reservation confirmed'}),'uncertain');assert.equal(classifyResult({url:'/reservations/complete',heading:'Error',text:'Reservation confirmed'}),'uncertain');assert.equal(classifyResult({url:'/reservations/complete',heading:'Waitlist registered'}),'waitlisted');assert.equal(classifyResult({url:'/reservations/complete',heading:'Unknown page'}),'uncertain');});
test('review checks identity, category, appointment date and time',()=>{const text=`VISA Application for short stay (Applicant) ${Object.values(sample).join(' ')} 2026/09/23 10:00`;assert.doesNotThrow(()=>verifyReview(text,sample,{date:'2026-09-23',time:'10:00'}));assert.throws(()=>verifyReview(text.replace('short stay','with COE'),sample,{date:'2026-09-23',time:'10:00'}));assert.throws(()=>verifyReview(text,sample,{date:'2026-09-24',time:'10:00'}));});
test('passport uniqueness and durable submit state prevent repeat bookings after restart',t=>{const store=db(t);const id=store.add(sample);assert.throws(()=>store.add({...sample,passport:'aa1234567'}));store.transition(id,'working');store.transition(id,'submitting');store.recover();assert.equal(store.get(id).state,'uncertain');assert.throws(()=>store.transition(id,'queued'));store.resolve(id,'booked');assert.throws(()=>store.resolve(id,'queued'));assert.throws(()=>store.transition(id,'working'));});
test('interrupted pre-submit work can resume; known results remain immutable',t=>{const store=db(t);const id=store.add(sample);store.transition(id,'working');store.recover();assert.equal(store.get(id).state,'queued');store.transition(id,'submitting');store.transition(id,'booked');store.recover();assert.equal(store.get(id).state,'booked');});
test('notification failure cannot change booked state; outbox deduplicates',async t=>{const store=db(t);const id=store.add(sample);store.transition(id,'submitting');store.transition(id,'booked');store.notify('once','BRON BOR');store.notify('once','BRON BOR');let fail=true;const notifier=new Notifier(store,{telegram_bot_token:'fake',owner_chat_id:'1'},async()=>{if(fail)throw Error('offline');return {ok:true,json:async()=>({ok:true})};});await notifier.flush();assert.equal(store.pending().length,1);assert.equal(store.get(id).state,'booked');fail=false;notifier.nextTry=0;await notifier.flush();assert.equal(store.pending().length,0);});
test('429 retry-after and global gate backoff apply to all workers',async()=>{assert.equal(retryAfter('60'),60000);assert.equal(retryAfter('invalid'),60000);const g=new Gate(10);const start=Date.now();g.backoff(60);await Promise.all([g.take(),g.take()]);assert.ok(Date.now()-start>=60);});
test('local API rejects cross-origin writes and masks passport in state',async t=>{const store=db(t);store.add(sample);const agent={running:false,status:()=>({running:false})};const notifier={configured:()=>true};const port=19473;const server=createServer({store,agent,notifier,port});await new Promise(r=>server.listen(port,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base=`http://127.0.0.1:${port}`;const state=await(await fetch(`${base}/api/state`)).json();assert.equal(state.candidates[0].passport,undefined);assert.equal(state.candidates[0].payload,undefined);const res=await fetch(`${base}/api/candidates`,{method:'POST',headers:{Origin:'https://evil.example','X-CSRF-Token':state.csrf},body:JSON.stringify(sample)});assert.equal(res.status,403);});
