'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {Store}=require('../core.cjs');const {Agent}=require('../booking.cjs');const {Bot,Notifier,TelegramAPI}=require('../telegram.cjs');const {Scheduler,validateSchedule}=require('../scheduler.cjs');
const sample={family:'TESTOV',given:'TEST',phone:'+998901234567',email:'test@example.invalid',passport:'AA1234567'};
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jp-telegram-'));const store=new Store(dir);t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});return store;}
function fakeAgent(){return {running:false,count:0,options:null,status:()=>({message:'Tayyor'}),start(o){this.count++;this.options=o;this.done=Promise.resolve();},async stop(){this.running=false;}};}
function botFixture(t){const store=fixture(t),agent=fakeAgent(),config={telegram_bot_token:'test-secret',owner_chat_id:'100'};const scheduler=new Scheduler(store,agent,config);const bot=new Bot(store,agent,scheduler,config,{now:()=>Date.parse('2026-09-16T10:00:00Z')});return {store,agent,bot,scheduler};}
function msg(id,text,from='100',type='private'){return {update_id:id,message:{text,date:1789552800,chat:{id:100,type},from:{id:Number(from)}}};}
test('Telegram: only configured owner in private chat can act',async t=>{const f=botFixture(t);await f.bot.handle(msg(1,'/run','101'));await f.bot.handle(msg(2,'/run','100','group'));assert.equal(f.agent.count,0);assert.equal(f.store.pending().length,0);await f.bot.handle(msg(3,'/run'));assert.equal(f.agent.count,1);});
test('Telegram: repeated update never executes booking twice',async t=>{const f=botFixture(t);await f.bot.handle(msg(7,'/run'));await f.bot.handle(msg(7,'/run'));assert.equal(f.agent.count,1);});
test('Telegram: stale commands cannot start real bookings after startup',async t=>{const f=botFixture(t),u=msg(1,'/run');u.message.date=1;await f.bot.handle(u);assert.equal(f.agent.count,0);});
test('Telegram: add wizard preserves values and list does not reveal passport',async t=>{const f=botFixture(t);for(const [i,text] of ['/add',sample.family,sample.given,sample.passport,sample.phone,sample.email].entries())await f.bot.handle(msg(i+1,text));assert.equal(f.store.list().length,1);assert.equal(f.store.list()[0].email,sample.email);await f.bot.handle(msg(10,'/list'));assert.ok(f.store.pending().every(m=>!m.message.includes(sample.passport)));});
test('Telegram: invalid passport is not accepted into queue',async t=>{const f=botFixture(t);for(const [i,text] of ['/add',sample.family,sample.given,'1234567',sample.phone,sample.email].entries())await f.bot.handle(msg(i+1,text));assert.equal(f.store.list().length,0);});
test('Telegram: no_booking does not unlock an already booked candidate',async t=>{const f=botFixture(t);const id=f.store.add(sample);f.store.transition(id,'submitting');f.store.transition(id,'booked');await f.bot.handle(msg(1,`/no_booking ${id.slice(0,8)}`));assert.equal(f.store.get(id).state,'booked');});
test('Telegram: cancel clears partially entered sensitive data',async t=>{const f=botFixture(t);await f.bot.handle(msg(1,'/add'));await f.bot.handle(msg(2,'TESTOV'));await f.bot.handle(msg(3,'/cancel'));assert.equal(f.store.setting('wizard',1),null);});
test('Telegram: end time and parallel count are validated and persisted',async t=>{const f=botFixture(t);await f.bot.handle(msg(1,'/end 20:00'));await f.bot.handle(msg(2,'/parallel 20'));assert.equal(f.bot.settings().end,'20:00');assert.equal(f.bot.settings().parallel,20);await f.bot.handle(msg(3,'/parallel 21'));assert.equal(f.bot.settings().parallel,20);});
test('scheduler: preparation starts at 18:55 Tashkent and booking waits until 19:00',async t=>{const store=fixture(t),agent=fakeAgent(),s=new Scheduler(store,agent,{prepareTime:'18:55',releaseTime:'19:00',endTime:'19:30',parallel:3});await s.tick(new Date('2026-09-16T13:54:59Z'));assert.equal(agent.count,0);await s.tick(new Date('2026-09-16T13:55:00Z'));assert.equal(agent.count,1);assert.equal(agent.options.startAt,'2026-09-16T19:00:00+05:00');assert.equal(agent.options.endAt,'2026-09-16T19:30:00+05:00');await s.tick(new Date('2026-09-16T14:01:00Z'));assert.equal(agent.count,1);await s.tick(new Date('2026-09-17T13:55:00Z'));assert.equal(agent.count,2);});
test('scheduler: resumes unfinished daily run after restart without a new run ID',async t=>{const store=fixture(t),agent=fakeAgent(),s=new Scheduler(store,agent);store.saveSetting('daily:2026-09-16',{finished:false,runId:'old-run'});await s.tick(new Date('2026-09-16T14:01:00Z'));assert.equal(agent.options.runId,'old-run');});
test('scheduler: stop_today and disabled schedule do not run again',async t=>{const store=fixture(t),agent=fakeAgent(),s=new Scheduler(store,agent);s.stopToday(new Date('2026-09-16T14:00:00Z'));await s.tick(new Date('2026-09-16T14:01:00Z'));assert.equal(agent.count,0);store.saveSetting('schedule',{enabled:false,prepare:'18:55',release:'19:00',end:'19:30',parallel:3});await s.tick(new Date('2026-09-17T14:01:00Z'));assert.equal(agent.count,0);});
test('scheduler: no late run after end time and invalid time is rejected',async t=>{const store=fixture(t),agent=fakeAgent(),s=new Scheduler(store,agent);await s.tick(new Date('2026-09-16T15:00:00Z'));assert.equal(agent.count,0);assert.throws(()=>validateSchedule({enabled:true,prepare:'18:55',release:'19:00',end:'18:00',parallel:3}));});
test('notifier: sends lossless PNG document with timestamp and owner destination',async t=>{const store=fixture(t);fs.writeFileSync(path.join(store.dir,'shot.png'),Buffer.from('89504e470d0a1a0a','hex'));store.notify('shot','BRON BOR. Gmailni tekshiring.',{file:'shot.png',capturedAt:'2026-09-16T14:00:00Z'});let call;const n=new Notifier(store,{telegram_bot_token:'fake',owner_chat_id:'100'},async(url,options)=>{call={url,body:options.body};return {ok:true,json:async()=>({ok:true,result:{}})};});await n.flush();assert.ok(call.url.endsWith('/sendDocument'));assert.equal(call.body.get('chat_id'),'100');assert.ok(call.body.get('caption').includes('Gmail'));assert.equal(call.body.get('document').type,'image/png');assert.equal(store.pending().length,0);});
test('notifier: 429 retains screenshot in outbox and respects Retry-After',async t=>{const store=fixture(t);store.notify('n','test');const n=new Notifier(store,{telegram_bot_token:'fake',owner_chat_id:'100'},async()=>({ok:false,status:429,json:async()=>({ok:false,error_code:429,parameters:{retry_after:60}})}));const before=Date.now();await n.flush();assert.ok(n.nextTry>=before+60000);assert.equal(store.pending().length,1);});
test('notifier: missing screenshot is explicitly reported, not silently dropped',async t=>{const store=fixture(t);store.notify('n','test',{file:'missing.png',capturedAt:new Date().toISOString()});let sent;const n=new Notifier(store,{telegram_bot_token:'fake',owner_chat_id:'100'},async(url,opts)=>{sent=JSON.parse(opts.body);return {ok:true,json:async()=>({ok:true})};});await n.flush();assert.match(sent.text,/fayli topilmadi/);});
test('store: result and notification commit atomically',t=>{const store=fixture(t),id=store.add(sample);store.transition(id,'submitting');const notify=store.notify;store.notify=()=>{throw Error('disk error');};assert.throws(()=>store.finish(id,'booked','ok',null,{key:'k',message:'booked'}));assert.equal(store.get(id).state,'submitting');store.notify=notify;store.finish(id,'booked','ok',null,{key:'k',message:'booked'});assert.equal(store.get(id).state,'booked');assert.equal(store.pending().length,1);});
test('report: outages never become a false no-slots claim',async t=>{const store=fixture(t),a=new Agent(store);a.runId='outage';a.stats={checks:2,errors:1,found:0,months:['2026-09-01','2026-10-01']};await a.report('deadline');assert.match(store.pending()[0].message,/TO‘LIQ TEKSHIRIB BO‘LMADI/);assert.doesNotMatch(store.pending()[0].message,/📭 JOY TOPILMADI/);});
test('report: valid empty calendars attach actual screenshot reference',async t=>{const store=fixture(t),a=new Agent(store);a.runId='empty';a.stats={checks:2,errors:0,found:0,months:['2026-09-01','2026-10-01']};a.evidence={'2026-09-01':{file:'evidence/test.png',capturedAt:new Date().toISOString(),month:'2026-09-01'}};await a.report('deadline');assert.match(store.pending()[0].message,/JOY TOPILMADI/);assert.equal(JSON.parse(store.pending()[0].media).file,'evidence/test.png');});
test('editing is blocked after submitting, booked, or uncertain',t=>{const store=fixture(t),id=store.add(sample);store.transition(id,'submitting');assert.throws(()=>store.update(id,sample));store.transition(id,'uncertain');assert.throws(()=>store.update(id,sample));});
